# This is a basic workflow to help you get started with Actions

name: install

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: test installer
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            dependencies_installer: bin/linux_apt_installer.sh
          - os: macos-latest
            dependencies_installer: bin/brew_installer.sh

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install.sh
        run: bash etc/install.sh

      - name: cargo installer
        run: bash bin/cargo_installer.sh

      - name: dependencies installer
        run: bash ${{ matrix.dependencies_installer }}

      - name: deploy
        run: make deploy

      - name: load
        run: zsh -c 'source ~/.zshrc'
